In [1]:
import numpy as np

In [2]:
data01 = np.arange(100, 0, -1) # 创建数组
data01

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [3]:
data01.sort() # 排序
data01

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
data01 = data01.reshape(4, 25) # 将数组data01变形成4行25列的2维数组
data01

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [5]:
data02 = np.random.random((3, 4)) # 创建一个大小为3行4列的2维随机数组
data02

array([[0.61409752, 0.72188936, 0.17028083, 0.19634284],
       [0.58336072, 0.59742395, 0.14322837, 0.66306055],
       [0.83113562, 0.40306137, 0.33992794, 0.10054132]])

In [6]:
data02[0:3, 1:4] # 选取数组data02后3列，也就是第2列到第4列元素
data02

array([[0.61409752, 0.72188936, 0.17028083, 0.19634284],
       [0.58336072, 0.59742395, 0.14322837, 0.66306055],
       [0.83113562, 0.40306137, 0.33992794, 0.10054132]])

In [7]:
data02.max() # 获取最大值

0.831135615422107

In [8]:
data02.min() # 获取最小值

0.10054132464907473

In [9]:
data02.sum() # 求和

5.36435040204181

In [10]:
data02.max(axis=0) # 获取每一列的最大值

array([0.83113562, 0.72188936, 0.33992794, 0.66306055])

In [11]:
data02.min(axis=0) # 获取每一列的最小值

array([0.58336072, 0.40306137, 0.14322837, 0.10054132])

In [12]:
data02.sum(axis=0) # 获取每一列的总和

array([2.02859386, 1.72237469, 0.65343715, 0.95994471])

In [13]:
data02.flatten() # 二维数组变成一维数组

array([0.61409752, 0.72188936, 0.17028083, 0.19634284, 0.58336072,
       0.59742395, 0.14322837, 0.66306055, 0.83113562, 0.40306137,
       0.33992794, 0.10054132])

In [14]:
data02.flatten().reshape(4, 3) # 将data02变成4行3列的2维数组

array([[0.61409752, 0.72188936, 0.17028083],
       [0.19634284, 0.58336072, 0.59742395],
       [0.14322837, 0.66306055, 0.83113562],
       [0.40306137, 0.33992794, 0.10054132]])