# Numpy的二维数组

## 1. 创建二维数组

如何创建一个二维数组呢？
你可以传递Python列表的列表来创建一个2d数组(或“矩阵”)来在NumPy中表示它们。

In [26]:
import numpy as np
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

![np_create_matrix](图片/np_create_matrix.png)

在一维数组的创建中，我们已经学会ones()， zeros()和random()，当然也可以使用ones()， zeros()和random()来创建一个2D数组，如果你给他们一个元组来描述矩阵的维数:

```python
>>> np.ones((3, 2))
array([[1., 1.],
       [1., 1.],
       [1., 1.]])
>>> np.zeros((3, 2))
array([[0., 0.],
       [0., 0.],
       [0., 0.]])
>>> rng.random((3, 2))
```

![np_ones_zeros_matrix](图片/np_ones_zeros_matrix.png)

## 2. 索引和切片

当你在操作矩阵时，索引和切片操作很有用:

In [10]:
data[0, 1]

2

In [11]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [12]:
data[0:2, 0]

array([1, 3])

![np_matrix_indexing](图片/np_matrix_indexing.png)

### 满足特定条件的切片 

如果想从数组中选择满足特定条件的值，使用NumPy很简单。

In [31]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

从a中选取小于10的子集：

In [32]:
below_five = a[a < 10]
below_five

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

或者是选取可以被2整除的子集：

In [25]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

选取满足多组条件下的子集：

In [34]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## 3. 数学运算

和一维数组一样，二维数组的求最大值、最小值和总和，如下：

In [14]:
data.max()

6

In [15]:
data.min()

1

In [16]:
data.sum()

21

![np_matrix_aggregation](图片/np_matrix_aggregation.png)

你可以在一个矩阵中聚合所有的值，你可以使用轴参数跨列或行聚合它们:

In [19]:
data.max(axis=0)

array([5, 6])

In [20]:
data.max(axis=1)

array([2, 4, 6])

![np_matrix_aggregation_row](图片/np_matrix_aggregation_row.png)

一旦你创建了你的矩阵，如果你有两个相同大小的矩阵，你可以使用算术运算符对它们进行相加和相乘

In [21]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

![np_matrix_arithmetic](图片/np_matrix_arithmetic.png)

你可以在不同大小的矩阵上做这些算术运算，但只有当一个矩阵只有一列或一行。在本例中，NumPy将使用它的广播规则进行操作。

In [22]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

![np_matrix_broadcasting](图片/np_matrix_broadcasting.png)

## 转置
通常需要对矩阵进行转置。NumPy数组有一个属性T，它允许你对一个矩阵进行转置

In [33]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

![np_transposing_reshaping](图片/np_transposing_reshaping.png)

## 变形

你可能还需要变换矩阵的维数。例如，当您有一个模型，它需要一个与您的数据集不同的输入形状时，就会发生这种情况。这就是重塑方法可以发挥作用的地方。你只需要传递你想要的矩阵的新维度。

```python
>>> data.reshape(2, 3)
array([[1, 2, 3],
       [4, 5, 6]])
>>> data.reshape(3, 2)
array([[1, 2],
       [3, 4],
       [5, 6]])
```

![np_reshape](图片/np_reshape.png)

如果想把2维数组变成1维，该如何操作呢？

In [35]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])