# Numpy的一维数组

## 1. Numpy的数组介绍

在学习python基础编程时，我们已经掌握了列表（Lists）的创建和使用。Numpy中的有一种数据结构叫：数组（Arrays）。它和Lists有什么不同呢？

- Numpy 数组比列表运行速度更快，更省计算机资源。
- 作为NumPy中主要的数据结构，数组是一些值组成的网格，它包含关于原始数据的信息，以及如何定位元素，意思是可以以各种方式对其进行索引。这些元素都是相同的类型，称为数组dtype。

数组可以由非负整数、元组、布尔值、另一个数组组成。数组的形状是一个整数元组，给出了数组的每个维度的大小。

初始化NumPy数组的一种方法是使用Python列表，对二维或高维数据使用嵌套列表。

举例，

In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2.关于数组的更多信息
您可能偶尔会听到一个数组被称为“ndarray”，它是“n维数组”的简写，d是单词dimension的缩写。n维数组就是具有任意维数的数组。你可能还听说过一维数组，二维数组，等等。NumPy ndarray用于表示矩阵和向量。向量是一维的数组(行向量和列向量没有区别)，而矩阵是二维的数组。对于三维或更高维度的数组，张量这个术语也常用。

数组通常是固定大小的容器，包含相同类型的项。数组中的维数和项数由数组的形状定义。数组的形状是由非负整数组成的元组，指定每个维度的大小。

在NumPy中，维度称为轴。这意味着如果你有一个像这样的2D数组:
```python
[[0., 0., 0.],
 [1., 1., 1.]]
```
数组有两个轴。第一个轴的长度是2，第二个轴的长度是3。

## 3.如何创建一个数组

In [5]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

用一种可视化方式来理解：

![ndarray](图片/np_array.png)

请注意，这些可视化是为了简化概念，并让您对NumPy概念和机制有一个基本的理解。

除了指定每个元素来创建数组之外，你还可以轻松创建一个由0填充的数组:

In [7]:
np.zeros(3)

array([0., 0.])

或者由1填充的数组：

In [8]:
np.ones(3)

array([1., 1.])

创建一组随机数:

In [38]:
np.random.random(3)

array([0.49126729, 0.10182265, 0.29090723])

![np_ones_zeros_random](图片/np_ones_zeros_random.png)

包含指定范围的数组：

In [9]:
np.arange(4)

array([0, 1, 2, 3])

甚至包含等距间隔的数组。为此，您需要指定第一个数字、最后一个数字和步长。下面这个例子，就是从2开始，到9结束，间隔为2。

In [10]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

你也可以使用np.linspace()来创建一个数组，该数组的值按指定的间隔线性排列:

In [8]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 4.指定你的数据类型

创建数组的时候，可以指定其中元素的类型，使用参数dtype。dtype可以等于np.int64, np.float64, np.str等等。

虽然默认的数据类型是浮点数(np.float64)，但您可以使用dtype关键字显式指定想要的数据类型。

In [32]:
a = np.array([1, 2, 3, 4, 5, 6], dtype=np.float64)
a

array([1., 2., 3., 4., 5., 6.])

现在尝试去索引第一个元素，也就是寻找第一个位置存储的元素。使用数组变量名和一对方括号[]，其中是一个从0开始到数组长度-1的整数

In [33]:
a[0]

1.0

这个数组的长度是6，它包含6个元素。如果使用`a[6]`去查找（索引）第六个元素，会怎样？猜一猜

In [34]:
a[6]

IndexError: index 6 is out of bounds for axis 0 with size 6

In [35]:
a[0], a[1], a[2], a[3], a[4], a[5] 

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)

### 练习

试试使用之前已经掌握的for循环来依次取出各个元素：

## 5.数组的形状和尺寸

`ndarray.ndim` 会告诉你数组的轴数，或者说是维度。

`ndarray.size` 会告诉你数组元素的总数。这是数组的形状元素的乘积。

`ndarray.shape` 将显示一个整数元组，该元组指示数组每个维度上存储的元素数量。例如，如果你有一个2行3列的2d数组，数组的形状是(2,3)。

In [16]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [17]:
array_example.ndim

3

In [18]:
array_example.size

24

In [19]:
array_example.shape

(3, 2, 4)

猜猜看以下数组的ndim、size、shape

In [20]:
array_example = np.array([[0, 1, 2, 3],
                          [4, 5, 6, 7],
                          [0, 1, 2, 3],
                          [4, 5, 6, 7],
                          [0 ,1 ,2, 3],
                          [4, 5, 6, 7]])

## 6.索引和切片

您可能希望获取数组的一部分或特定数组元素，以便在进一步的分析或其他操作中使用。要做到这一点，您需要对数组进行子集、切片和/或索引。

就像使用列表(lists)一样，你可以用同样的方式索引和切片，选择数组中的部分元素。

```python
>>> data = np.array([1, 2, 3])

>>> data[1]
2
>>> data[0:2]
array([1, 2])
>>> data[1:]
array([2, 3])
>>> data[-2:]
array([2, 3])
```

下面用一种可视化的方式：

![np_indexing.png](图片/np_indexing.png)

## 7.数组的操作方法

### 排序数组元素

使用np.sort()对元素进行排序很简单。您可以在调用函数时指定轴、类型和顺序。

In [1]:
import numpy as np
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

你可以按照升序进行排序:

In [2]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

除了sort(返回数组的已排序副本)，您还可以使用:
- argsort，它是沿着指定轴进行间接排序，
- lexsort，是对多个键的间接稳定排序，
- searchsorted，它将在已排序的数组中查找元素
- partition，这是一种部分排序。

### 连结两个数组

In [3]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

可以使用np.concatenate()将它们连接起来。

In [4]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

或者是另一个方向，

In [6]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

你把它们拼接在一起

In [7]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 数学运算

一旦创建了数组，就可以开始使用它们了。比如说，你创建了两个数组，一个叫data，一个叫ones。

![np_array_dataones](图片/np_array_dataones.png)

In [10]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

![np_data_plus_ones](图片/np_data_plus_ones.png)

In [11]:
data - ones

array([0, 1])

In [12]:
data * data

array([1, 4])

In [13]:
data / data

array([1., 1.])

![np_sub_mult_divide](图片/np_sub_mult_divide.png)

### 求和、最大值、最小值

如果是对数组内部的元素求和：

In [15]:
a = np.array([1, 2, 3, 4])
a.sum()

10

如果是2维数组，您需要指定轴，axis=0是按照列的方向，axis=1按照行的方向求和。

In [20]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [21]:
b.sum(axis=0)

array([3, 3])

In [22]:
b.sum(axis=1)

array([2, 4])

NumPy还执行聚合函数。除了min、max和sum之外，您还可以轻松地运行mean以得到平均值，prod以得到元素相乘的结果，std以得到标准差，等等。

In [25]:
data = np.array([1, 2, 3])
data.max()

3

In [26]:
data.min()

1

In [27]:
data.sum()

6

![np_aggregation](图片/np_aggregation.png)